// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjnmkgpbdxmjlrliuags.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdqbm1rZ3BiZHhtamxybGl1YWdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2NDkzNzIsImV4cCI6MjA2ODIyNTM3Mn0.kYRf6BnB0IH7BLvoFZrAODd_-UWz713_2PdmjsY_Rlc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});